version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 7700 --reload
    volumes:
      - .:/app
    environment:
      APP_ENV: local
      PORT: 7700
      LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/aksara
      VECTOR_DIM: 1536
      GEMINI_API_KEY: ${GEMINI_API_KEY:-changeme}
      GEMINI_MODEL_QA: gemini-2.5-pro
      GEMINI_MODEL_EMBED: text-embedding-004
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:7900}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BUCKET_DOCUMENTS: ${MINIO_BUCKET_DOCUMENTS:-documents}
      MINIO_PRESIGNED_TTL: ${MINIO_PRESIGNED_TTL:-3600}
      MINIO_PUBLIC_ENDPOINT: ${MINIO_PUBLIC_ENDPOINT:-http://localhost:7900}
      MINIO_USE_SSL: ${MINIO_USE_SSL:-false}
      MINIO_REGION: ${MINIO_REGION:-}
      ENABLE_PDF_EXPORT: 'false'
      RETRIEVAL_TOPK: 24
      RERANK_TOPK: 8
      JWT_ISSUER: https://auth.aksara.id/
      JWT_AUDIENCE: aksara-legal-ai
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      LIBREOFFICE_BINARY: soffice
    ports:
      - "7700:7700"
    depends_on:
      - postgres
    networks:
      - aksara_network

  postgres:
    image: ankane/pgvector:pg16
    environment:
      POSTGRES_DB: aksara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aksara_network

volumes:
  pgdata:

networks:
  aksara_network:
    external: true
