services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "7600:3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "node -e \"const http=require('http');const req=http.request({host:'127.0.0.1',port:3000,path:'/'},res=>{process.exit(res.statusCode<500?0:1);});req.on('error',()=>process.exit(1));req.setTimeout(2000,()=>{req.destroy();process.exit(1);});req.end();\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  minio:
    image: minio/minio
    restart: unless-stopped
    command: server --address ":7900" /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7900/minio/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - minio_data:/data
    ports:
      - "7900:7900"
      - "9001:9001"

  minio-init:
    image: minio/minio
    depends_on:
      minio:
        condition: service_started
    entrypoint: >-
      /bin/sh -c "
      until mc alias set local http://minio:7900 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do sleep 2; done && \
      mc mb --ignore-existing local/${MINIO_BUCKET_DOCUMENTS} && \
      mc anonymous set private local/${MINIO_BUCKET_DOCUMENTS}
      "
    restart: "no"

volumes:
  postgres_data:
  minio_data:
