export enum NotificationType {
  ACCOUNT_REGISTERED = 'ACCOUNT_REGISTERED',
  BUSINESS_PROFILE_COMPLETED = 'BUSINESS_PROFILE_COMPLETED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_REPLACED = 'DOCUMENT_REPLACED',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  CHECKLIST_READY = 'CHECKLIST_READY',
  GENERIC = 'GENERIC',
}
