export const SUBSCRIPTION_PLAN_REPOSITORY = Symbol(
  'SUBSCRIPTION_PLAN_REPOSITORY',
);
export const SUBSCRIPTION_REPOSITORY = Symbol('SUBSCRIPTION_REPOSITORY');
export const PAYMENT_TRANSACTION_REPOSITORY = Symbol(
  'PAYMENT_TRANSACTION_REPOSITORY',
);
